### ISSUE TITLE
could you share which camera you used and how to set the light  in details? thanks~

### ISSUE THREAD

**Issue by visonpon** [hjoonpark/MultiCamCalib#1]

**Comment by hjoonpark** [comment]
[https://arxiv.org/pdf/2102.07343.pdf](https://arxiv.org/pdf/2102.07343.pdf)
Our multicamera setup contains 16 standard (RGB) cameras arranged into a circle surrounding the capture volume (Fig. 3b). Each camera captures 4000×2160 images at 30 FPS in RAW format. The camera shutters are synchronized via genlock
with negligible synchronization error, which means that human motion is captured as if “frozen” in time. Surrounding the capture volume, we positioned 32 softboxes that generate uniform diffuse light. The bright light allows us to use a small aperture and very fast 0.5𝑚𝑠 shutter speeds, guaranteeing sharp images even with the fastest human motions.

**Comment by visonpon** [comment]
it's my bad that i didn't express clearly, what I want to know it's the exact type of camera you used.thanks~

**Comment by hjoonpark** [comment]
The camera was Blackmagic URSA Mini 4k EF,
with lenses Rokinon 10mm F2.8,
and the light was from FOVITEC - I don't remember the exact model name
